import { PortfolioItem } from "./types/portfolio.types"

export const portfolioItems: PortfolioItem[] = [
  {
    id: 1,
    title: "Senhora dos Afogados",
    coverImage: "https://drive.google.com/file/d/1c8v4ABlZQ8T-MBAfvrXDIrNiJzlnZI3Z/view?usp=sharing",
    description: "Peça teatral baseada no livro de mesmo nome, que conta a história de uma comunidade ribeirinha e seus desafios com as enchentes e a luta pela sobrevivência.",
    images: [
      "https://drive.google.com/file/d/1c8v4ABlZQ8T-MBAfvrXDIrNiJzlnZI3Z/view?usp=sharing",
      "https://drive.google.com/file/d/1cK8ksgg6cUbSAyCf5hrnr1xXYjiY6QYN/view?usp=sharing",
      "https://drive.google.com/file/d/1c8v4ABlZQ8T-MBAfvrXDIrNiJzlnZI3Z/view?usp=sharing",
      "https://drive.google.com/file/d/1cK8ksgg6cUbSAyCf5hrnr1xXYjiY6QYN/view?usp=sharing",
    ],
    videos: [
      "https://www.youtube.com/watch?v=21mDekTZwsw",
    ],
    year: "2024",
    category: "Teatro",
  },
  {
    id: 2,
    title: "Banda de Rock Alternativo",
    coverImage: "https://drive.google.com/file/d/1cK8ksgg6cUbSAyCf5hrnr1xXYjiY6QYN/view?usp=sharing",
    description: "Projeto musical com uma banda de rock alternativo, incluindo composições originais, gravações em estúdio e apresentações ao vivo em festivais locais.",
    images: [
      "https://drive.google.com/file/d/1rh3-C8KTaN3Z56J0DLD_VVatS-bCa6Mi/view?usp=sharing",
      "https://drive.google.com/file/d/1cK8ksgg6cUbSAyCf5hrnr1xXYjiY6QYN/view?usp=sharing",
      "https://drive.google.com/file/d/1rh3-C8KTaN3Z56J0DLD_VVatS-bCa6Mi/view?usp=sharing",
    ],
    videos: [],
    year: "2024",
    category: "Música",
  },
  {
    id: 3,
    title: "Desenho animado",
    coverImage: "https://drive.google.com/file/d/1rh3-C8KTaN3Z56J0DLD_VVatS-bCa6Mi/view?usp=sharing",
    description: "Curta-metragem de animação 2D que conta a história de um jovem aventureiro em uma jornada para salvar seu mundo de uma ameaça iminente, utilizando técnicas tradicionais de animação quadro a quadro.",
    images: [
      "https://drive.google.com/file/d/1rh3-C8KTaN3Z56J0DLD_VVatS-bCa6Mi/view?usp=sharing",
      "https://drive.google.com/file/d/1c8v4ABlZQ8T-MBAfvrXDIrNiJzlnZI3Z/view?usp=sharing",
      "https://drive.google.com/file/d/1rh3-C8KTaN3Z56J0DLD_VVatS-bCa6Mi/view?usp=sharing",
    ],
    videos: [],
    year: "2023",
    category: "Dublagem",
  },
  {
    id: 4,
    title: "Herança Maldita",
    coverImage: "https://drive.google.com/file/d/1cK8ksgg6cUbSAyCf5hrnr1xXYjiY6QYN/view?usp=sharing",
    description: "Peça teatral de suspense e mistério que gira em torno de uma família que herda uma mansão antiga, apenas para descobrir que ela esconde segredos sombrios e uma maldição que ameaça suas vidas.",
    images: [
      "https://drive.google.com/file/d/1cK8ksgg6cUbSAyCf5hrnr1xXYjiY6QYN/view?usp=sharing",
      "https://drive.google.com/file/d/1c8v4ABlZQ8T-MBAfvrXDIrNiJzlnZI3Z/view?usp=sharing",
      "https://drive.google.com/file/d/1cK8ksgg6cUbSAyCf5hrnr1xXYjiY6QYN/view?usp=sharing",
    ],
    videos: [],
    year: "2024",
    category: "Teatro",
  },
  {
    id: 5,
    title: "Zimba Geek Fest",
    coverImage: "https://drive.google.com/file/d/1cK8ksgg6cUbSAyCf5hrnr1xXYjiY6QYN/view?usp=sharing",
    description: "Evento anual de cultura pop e tecnologia que reúne fãs de quadrinhos, filmes, jogos e inovação, com palestras, workshops, competições e exposições interativas.",
    images: [
      "https://drive.google.com/file/d/1cK8ksgg6cUbSAyCf5hrnr1xXYjiY6QYN/view?usp=sharing",
      "https://drive.google.com/file/d/1c8v4ABlZQ8T-MBAfvrXDIrNiJzlnZI3Z/view?usp=sharing",
    ],
    videos: [],
    year: "2023",
    category: "Apresentação",
  },
  {
    id: 6,
    title: "Espetáculo de Dança Contemporânea",
    coverImage: "https://drive.google.com/file/d/1kTMcxTFGAtg5pyPbXOeW-urnyuNEyKY0/view?usp=sharing",
    description: "Peça de dança contemporânea que explora temas sociais e emocionais através de movimentos e expressões artísticas.",
    images: [
      "https://drive.google.com/file/d/1kTMcxTFGAtg5pyPbXOeW-urnyuNEyKY0/view?usp=sharing",
      "https://drive.google.com/file/d/1c8v4ABlZQ8T-MBAfvrXDIrNiJzlnZI3Z/view?usp=sharing",
      "https://drive.google.com/file/d/1kTMcxTFGAtg5pyPbXOeW-urnyuNEyKY0/view?usp=sharing",
    ],
    videos: [],
    year: "2024",
    category: "Dança",
  },
]